- name:
  debug:
    msg: "[WORKER] K8S_TOKEN_HOLDER - The token is {{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"

- name:
  debug:
    msg: "[WORKER] K8S_TOKEN_HOLDER - The hash is {{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}"

- name: Remove cluster
  command:
    kubeadm reset --force
  register: kubeadm_reset

- name: Add the worker node into the kubernetes cluster.
  shell:
    kubeadm join --token={{ hostvars['K8S_TOKEN_HOLDER']['token'] }} --discovery-token-ca-cert-hash sha256:{{ hostvars['K8S_TOKEN_HOLDER']['hash'] }} {{K8S_MASTER_NODE_PRIVATE_IP}}:{{K8S_API_SECURE_PORT}}

